source 'https://rubygems.org'

gem 'haml'
gem 'httparty'
gem 'json'
gem 'mysql2'
gem 'rubocop'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rotp', :git => 'https://github.com/mdp/rotp', :branch => 'v4.0'
gem 'rqrcode'
